export const AUTHETICATION_SET_AUTH_TOKEN = 'AUTHETICATION_SET_AUTH_TOKEN';
export const AUTHENTICATION_SET_LOGOUT = 'AUTHENTICATION_SET_LOGOUT';

export const CLIENT_FIND_ALL = 'CLIENT_FIND_ALL';

export const VIACEP_FIND_BY_CEP = 'VIACEP_FIND_BY_CEP';